catalog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.index, name="index"),
    path("books", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book"),
    path(
        "book_instance/borrowed",
        views.BorrowedBookInstancesListView.as_view(),
        name="book-instance-borrowed",
    ),
    path(
        "book/instance/<uuid:pk>/reserve",
        views.reserve_book_form,
        name="reserve-book-form",
    ),
    path(
        "book/instance/<uuid:pk>/set_loaned",
        views.set_book_loaned_form,
        name="set-loaned-book-form",
    ),
    path("author/create", views.AuthorCreateView.as_view(), name="author-create"),
    path(
        "author/update/<int:pk>", views.AuthorUpdateView.as_view(), name="author-update"
    ),
    path(
        "author/delete/<int:pk>", views.AuthorDeleteView.as_view(), name="author-delete"
    ),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", RedirectView.as_view(url="catalog/")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
]

catalog/models.py
from django.db import models
import uuid

from django.contrib.auth.models import User

# Create your models here.


class Author(models.Model):
    name = models.CharField(
        max_length=100,
        null=False,
        help_text="An author's full name. (Example: W. Shakespear or Mihail Afanasievich Bulgakov)",
    )
    date_of_birth = models.DateField(
        null=True,
        blank=True,
        help_text="A date of author's birth (or Null, if unknown).",
    )
    date_of_death = models.DateField(
        null=True,
        blank=True,
        help_text="A date of author's death (or Null, if alive or unknown).",
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return f"/catalog/author/{self.pk}"


class Genre(models.Model):
    name = models.CharField(
        max_length=100, help_text="A book genre. (example: Science Fiction)"
    )

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    summary = models.TextField()
    language = models.CharField(max_length=100)
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    genres = models.ManyToManyField(Genre)

    def __str__(self) -> str:
        return f"{self.author.name} - {self.title!r}"

    def get_absolute_url(self) -> str:
        return f"/catalog/book/{self.pk}"


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    imprint = models.CharField(max_length=100)
    year = models.SmallIntegerField()
    book = models.ForeignKey(Book, null=False, on_delete=models.CASCADE)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        permissions = [
            ("can_mark_returned", "Set book as returned"),
            ("can_mark_on_loan", "Set book as on loan"),
        ]

    LOAN_STATUS = (
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1, choices=LOAN_STATUS, default="a", null=False
    )
    due_back = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{str(self.id)[:8]} ({self.book})"

    def get_display_status(self) -> str:
        return dict(self.LOAN_STATUS)[self.status] + (
            "" if self.status != "o" else f" until {self.due_back}"
        )

catalog/forms.py
from django.core.exceptions import ValidationError
from django import forms
from datetime import date
from .models import BookInstance


class ReserveBookForm(forms.Form):
    return_date = forms.DateField(
        help_text="Enter a date, at least today.", required=True
    )

    def clean_return_date(self):
        data = self.cleaned_data["return_date"]

        if data < date.today():
            raise ValidationError("Invaid date - return in the past")

        return data


class BookInstanceEditForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ["status", "due_back"]

        help_texts = {
            "status": "Change current book instance status",
            "due_back": "Enter a date, at least today.",
        }

    def clean_due_back(self):
        data = self.cleaned_data["due_back"]

        if data < date.today():
            raise ValidationError("Invaid date - return in the past")

        return data

catalog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Book, Author, BookInstance, Genre
from .forms import ReserveBookForm
from typing import Any


import datetime

# Create your views here.


class AuthorCreateView(generic.CreateView):
    model = Author
    fields = "__all__"
    initial = {
        "date_of_death": "11/03/2009",
    }


class AuthorUpdateView(generic.UpdateView):
    ...


class AuthorDeleteView(generic.DeleteView):
    ...


class BookListView(generic.ListView):
    model = Book
    context_object_name = "book_list"
    queryset = Book.objects.all()
    template_name = "book/list.html"

    # def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
    #     return super().get_context_data(**kwargs) | {"book_list": Book.objects.all()}


class BorrowedBookInstancesListView(LoginRequiredMixin, generic.ListView):
    model = Book
    context_object_name = "book_instance_list"
    # queryset = BookInstance.objects.filter(borrower=)
    template_name = "book_instance/list.html"

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user)


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book
    template_name = "book/detail.html"


VISITS_KEY = "visits"


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Author.objects.all().count()

    num_visits = request.session.get(VISITS_KEY, 0)
    request.session[VISITS_KEY] = num_visits + 1

    return render(
        request,
        "index.html",
        context={
            "num_books": num_books,
            "num_instances": num_instances,
            "num_instances_available": num_instances_available,
            "num_authors": num_authors,
            "num_visits": num_visits,
        },
    )


@login_required
def reserve_book_form(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == "POST":
        form = ReserveBookForm(request.POST)

        if form.is_valid():
            # Perform action
            book_instance.status = "r"
            book_instance.due_back = form.cleaned_data["return_date"]
            book_instance.borrower = request.user

            book_instance.save()

            # Redirect to success url
            return HttpResponseRedirect("/")

    else:
        proposed_return_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = ReserveBookForm(initial={"return_date": proposed_return_date})

    return render(
        request,
        "book/reserve.html",
        {"form": form, "book_instance": book_instance},
    )


@permission_required("can_mark_on_loan")
def set_book_loaned_form(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == "POST":
        form = ReserveBookForm(request.POST)

        if form.is_valid():
            # Perform action
            book_instance.status = "o"

            book_instance.save()

            # Redirect to success url
            return HttpResponseRedirect("/")

    else:
        proposed_return_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = ReserveBookForm(initial={"return_date": proposed_return_date})

    return render(
        request,
        "book/set_loaned.html",
        {"form": form, "book_instance": book_instance},
    )

catalog/templates/base_generic.html
<!DOCTYPE html>
<html>
    <head>
        {% block title %}
        <title>Local Library</title>
        {% endblock %}

        <!-- Latest compiled and minified CSS -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous"
        />

        <!-- Optional theme -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous"
        />

        <!-- Jquery -->
        <script
            src="https://code.jquery.com/jquery-1.12.4.js"
            integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
            crossorigin="anonymous"
        ></script>

        <!-- Latest compiled and minified JavaScript -->
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"
        ></script>

        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'books' %}">All books</a></li>
                        <li><a href="">All authors</a></li>
                        <li><br /></li>
                        {% if user.is_authenticated %}
                        <li>User: {{user.get_username}}</li>
                        <li><a href="{% url 'book-instance-borrowed' %}">My books</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %}
                    <!-- default content-->
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

catalog/templates/book/detail.html
{% extends "base_generic.html" %} {% block content %}

<h1>Title: {{object.title}}</h1>

<p><strong>Author:</strong> {{ object.author }}</p>
<p><strong>Summary:</strong> {{ object.summary }}</p>
<p>
    <strong>Genres:</strong>
    {% for genre in object.genres.all %} {{ genre }}{% if not forloop.last %}, {%endif%} {% endfor %}
</p>
<p><strong>Language:</strong> {{ object.language }}</p>

<div style="margin-top: 60px">
    <h4>Copies</h4>

    {% for copy in object.bookinstance_set.all %}
    <hr />
    <p
        class="{% if copy.status == 'a'%}text-success{% elif copy.status == 'o' %}text-danger{% else %}text-warning{% endif %}"
    >
        {{copy.get_display_status}} 
        {% if copy.status == 'a'%} -
            <a href=" {% url 'reserve-book-form' copy.pk %} ">Reserve</a> 
        {% elif copy.status == 'r' and perms.catalog.can_mark_on_loan %} 
            <a href=" {% url 'set-loaned-book-form' copy.pk %} ">Set loaned</a> 
        {% endif %}
    </p>
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p><strong>Year:</strong> {{copy.year}}</p>
    <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>

    {% endfor %}
</div>

{% endblock %}

catalog/templates/book/list.html
{% extends "base_generic.html" %} {% block content %}

<h1>Book list</h1>

{% if book_list %}

<ul>
    {% for book in book_list %}
    <li><a href="{{ book.get_absolute_url }}"> {{ book.title }}</a> {{ book.author }}</li>
    {% endfor %}
</ul>

{% else %}

<p>There are no books :c</p>

{% endif %} {% endblock %}

catalog/templates/book/reserve.html
{% extends "base_generic.html" %} {% block content %}

<h1>Reserve: {{ book_instance.book.title }}</h1>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

catalog/templates/book/set_loaned.html
{% extends "base_generic.html" %} {% block content %}

<h1>Set loaned: {{ book_instance.book.title }}</h1>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

catalog/templates/book_instance/list.html
{% extends "base_generic.html" %} {% block content %}

<div style="margin-top: 60px">
    <h4>Rented books</h4>

    {% if book_instance_list %} {% for copy in book_instance_list %}
    <hr />
    <p
        class="{% if copy.status == 'a'%}text-success{% elif copy.status == 'o' %}text-danger{% else %}text-warning{% endif %}"
    >
        {{copy.get_display_status}} {% if copy.status == 'a'%} -
        <a href=" {% url 'reserve-book-form' copy.pk %} ">Reserve</a> {% endif %}
    </p>
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p><strong>Year:</strong> {{copy.year}}</p>
    <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>

    {% endfor %} {% else %}
    <p>You have no rented books</p>
    {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %} {% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %} {% block content %}
<h1>Welcome to library!</h1>
<p>Welcome to <em>LocalLibrary</em>, a web application made on Django Framework</p>

{% if num_visits > 0 %}
<p>Тут могла быть Ваша реклама</p>
{% endif %}

<h2>Dynamic data</h2>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Book instances:</strong> {{ num_instances }}</li>
    <li><strong>Book instances (available):</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>You visited this page:</strong> {{ num_visits }} times</li>
</ul>
{% endblock %}